version: "3.8"
services:
  app:
    command: /bin/bash -c "yarn && yarn dev"
    build: ./batch-action
    working_dir: /app
    volumes:
      - ./batch-action:/app
      - node_modules:/app/node_modules
    environment:
      GID: 1000
      UID: 1000
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
    user: "1000:1000"
    tty: true
  tf:
    image: hashicorp/terraform:1.1.3
    working_dir: /workspace
    environment:
      HEROKU_API_KEY: ${HEROKU_API_KEY}
      HEROKU_EMAIL: ${HEROKU_EMAIL}
      TF_VAR_heroku_app_name: ${TF_VAR_heroku_app_name}
    volumes:
      - ./terraform:/workspace:cached
  # hasura:
  #   build: ./hasura
  #   ports:
  #     - "9693:9693"
  #     - "9695:9695"
  #   environment:
  #     HASURA_RUN_CONSOLE: true
  #     HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
  #     HASURA_GRAPHQL_ENDPOINT: http://graphql-engine:8080
  #   volumes:
  #     - ./hasura:/usr/src/hasura
  #   depends_on:
  #     - graphql-engine
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  hasura-engine:
    build: ./hasura
    ports:
      - "9693:9693"
      - "9695:9695"
      - "8080:8080"
    volumes:
      - ./hasura:/usr/src/hasura
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_RUN_CONSOLE: true
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  node_modules:
  db_data: