version: "3.7"
services:
  app:
    command: /bin/bash -c "yarn && yarn dev"
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      GID: 1000
      UID: 1000
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
    user: "1000:1000"
    tty: true
volumes:
  node_modules: