version: "3.7"
services:
  app:
    command: /bin/bash -c "yarn && yarn dev"
    build: ./batch-action
    working_dir: /app
    volumes:
      - ./batch-action:/app
      - node_modules:/app/node_modules
    environment:
      GID: 1000
      UID: 1000
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
    user: "1000:1000"
    tty: true
  tf:
    image: hashicorp/terraform:1.1.3
    working_dir: /workspace
    environment:
      HEROKU_API_KEY: ${HEROKU_API_KEY}
      HEROKU_EMAIL: ${HEROKU_EMAIL}
      TF_VAR_heroku_app_name: ${TF_VAR_heroku_app_name}
    volumes:
      - ./terraform:/workspace:cached
volumes:
  node_modules: