name: Exec
on:
  schedule:
    # UTC
    - cron: "* 3 * * 1" # JPN 12:00 Mon
  workflow_dispatch:

# 環境変数の設定
# repository secrets から取得した環境変数を設定する
env:
  # Discord Webhook URL
  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

jobs:
  build-and-test-and-exec:
    runs-on: ubuntu-latest
    # 実行する dir を指定
    defaults:
      run:
        shell: bash
        working-directory: batch-action
    steps:
    # checkout release branch
    - uses: actions/checkout@v2
      with:
        ref: release
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: install
      run: npm install
    - name: build
      run: npm run all
    - name: execute
      run: node dist/index.js