name: Test
on: push

env:
  GRAPHQL_ENDPOINT: http://graphql-engine:8080/v1/graphql
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: default

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # 実行する dir を指定
    defaults:
      run:
        shell: bash
        working-directory: batch-action
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: npm install, build, lint and test
        run: |
          docker-compose run app /bin/bash -c "npm run all"
