name: Test
on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # 実行する dir を指定
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - uses: actions/cache@v2
        with:
          path: ./batch-action/node_modules
          key: ${{runner.os}}-nodemodules-${{ hashFiles('**/package_lock.json') }}
      - name: npm install, lint, test and build
        run: |
          chmod a+w -R ./batch-action
          docker-compose run --rm app /bin/bash -c "dum check-build"
